Filtering special characters during automatic linking of ingredients …
mealie-recipes/mealie pull request #1836
Opened 2022-11-16 21:19 UTC by jenscalaerts

…to instructions

Used a unicode group to have a set of all unicode punctuation marks

## What type of PR is this?

- bug

## What this PR does / why we need it:

_(REQUIRED)_
The pull request aims to improve 

## Which issue(s) this PR fixes:
Fixes #1803 

## Testing
Create recipe with ingredients:
* 2 eggs
* 3 potatoes
* 5 carrots
* 2 steaks
Create an instruction with containing words matching ingredients, who have punctuation marks or formatting characters attached to them. For example, "add the **eggs**  to the potatoes, then mix".

## Release Notes

_(REQUIRED)_
```Fixed bug where steps were not automatically linked to ingredients when special characters are attached to the word.
```

2022-11-27 20:41 UTC, hay-kot requested changes
Could you pull this function into a composable and provide a unit test for it? Other than that it looks great!

2022-12-13 09:51 UTC, jenscalaerts commented
I have added filtering for 2 letter words in the instruction. They seemed to generate a large amount of false positives (in Dutch). This seems like a good idea because most languages have few 2 letter ingredients. It also replaces a large part of the blacklist, which has no internationalization.

2022-12-29 21:59 UTC, hay-kot commented
Excellent, thanks so much for following up with tests!

2022-12-29 21:59 UTC, hay-kot approved these changes

2022-12-29 22:00 UTC, merged