Update docker-compose.yml
mealie-recipes/mealie pull request #2109
Opened 2023-02-09 20:43 UTC by rocket357

ERROR: The Compose file './docker-compose.yml' is invalid because: services.mealie.environment.WEB_GUNICORN contains true, which is an invalid type, it should be a string, number, or a null

## What type of PR is this?

- bug

## What this PR does / why we need it:

ERROR: The Compose file './docker-compose.yml' is invalid because:
services.mealie.environment.WEB_GUNICORN contains true, which is an invalid type, it should be a string, number, or a null

## Which issue(s) this PR fixes:

N/A - Should I open an issue first, or is jumping straight to PR sufficient?

## Special notes for your reviewer:

None, simple fix.

## Testing

```
docker01:~# docker version
Client:
 Version:           20.10.16
 API version:       1.41
 Go version:        go1.18.2
 Git commit:        aa7e414fdcb23a66e8fabbef0a560ef1769eace5
 Built:             Sun May 15 14:51:52 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server:
 Engine:
  Version:          20.10.16
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.18.2
  Git commit:       f756502055d2e36a84f2068e6620bea5ecf09058
  Built:            Sun May 15 14:46:21 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.6.6
  GitCommit:        10c12954828e7c7c9b6e0ea9b0c02b01407d3ae1
 runc:
  Version:          1.1.2
  GitCommit:        a916309fff0f838eb94e928713dbc3c0d0ac7aa4
 docker-init:
  Version:          0.19.0
  GitCommit:
```

## Release Notes

N/A

2023-02-09 21:35 UTC, rocket357 commented
Updated the PR to fix a few issues I ran into on enabling SMTP as well.  If I need to split anything off (since it was a basic bugfix to begin with), please let me know!  =)

2023-02-11 19:20 UTC, hay-kot requested changes
Can you remove the rest of the changes, or let me know why we need to make these changes if it's no intended for end users?

2023-02-11 19:20 UTC, hay-kot commented on docker/docker-compose.yml
> +      WEB_GUNICORN: "true"
This is the only change I think is warranted. 

This docker-compose file is meant for end users so the annotations aren't super useful. For end-users you should be using the documentation. This also doesn't seem to be a problem on newer versions of docker-compose? 🤷 

- https://nightly.mealie.io/documentation/getting-started/installation/postgres/

Configuration is also documented 

- https://nightly.mealie.io/documentation/getting-started/installation/backend-config/
- https://nightly.mealie.io/documentation/getting-started/installation/frontend-config/

2023-02-11 20:21 UTC, rocket357 commented
Yep, I got a little over-zealous making changes =)

I'll revert the other two commits.  Thanks!

2023-02-12 06:08 UTC, merged