Feature: add password reset token endpoint to the admin panel
mealie-recipes/mealie pull request #2171
Opened 2023-02-24 14:51 UTC by cmintey

## What type of PR is this?

- feature

## What this PR does / why we need it:

This PR adds a password reset link in the admin panel for each user. This link will allow the administrator to generate a password reset link for a user so as not to require the use of SMTP as discussed [here](https://github.com/hay-kot/mealie/pull/2143#issuecomment-1442254353)

## Which issue(s) this PR fixes:

None

## Testing

Tested visually that the button shows up and works.
Manually tested that the endpoint could only be called with an admin JWT.

## Release Notes

```release-note
admins can now generate password reset links without setting up SMTP
```

## Screenshots
![image](https://user-images.githubusercontent.com/35710697/221208385-9b13aeb8-ef9d-47f6-b631-b8388c3a5b11.png)

After url generation, the copy button shows up
![image](https://user-images.githubusercontent.com/35710697/221208453-60d4c553-f4d9-439e-b01e-62aa47f1cb4d.png)

2023-02-24 23:09 UTC, fleshgolem submitted a review, later dismissed

2023-02-26 19:15 UTC, hay-kot requested changes

2023-02-26 19:15 UTC, hay-kot commented on frontend/pages/admin/manage/users/_id.vue
> +              Generate Password Reset Link
Can you add this as a translatable string in the en-US.json file? Probably here

https://github.com/hay-kot/mealie/blob/refactor/global-exception-handling/frontend/lang/messages/en-US.json#L698

2023-02-27 15:10 UTC, cmintey commented on frontend/pages/admin/manage/users/_id.vue
> +              Generate Password Reset Link
Sure can

2023-03-12 20:33 UTC, merged