fix: SQLAlchemy auto-refreshes models during migration
mealie-recipes/mealie pull request #2773
Opened 2023-11-29 15:26 UTC by michael-genson

## What type of PR is this?

_(REQUIRED)_

- bug

## What this PR does / why we need it:

_(REQUIRED)_

Building off of https://github.com/mealie-recipes/mealie/pull/2760, another issue came up where committing the transaction was executing the faulty SELECT statement. This PR should prevent this by disabling auto refreshes after commits for this session.

## Which issue(s) this PR fixes:

_(REQUIRED)_

Mentioned in https://github.com/mealie-recipes/mealie/issues/2769

## Testing

_(fill-in or delete this section)_

Pulled a backup from an older version with dupes and confirmed it migrates correctly now.

2023-11-29 22:12 UTC, zierbeek commented
could you maybe give my backup a test?

2023-11-29 22:14 UTC, michael-genson commented
Sure, do you have a link?

2023-11-29 22:14 UTC, zierbeek commented
[Uploading mealie_2023.11.10.14.35.55.zip…]()

Yes!

2023-11-29 22:17 UTC, michael-genson commented
Might need to re-upload, GitHub doesn't seem to like it. It also might be too bug for GH:

![image](https://github.com/mealie-recipes/mealie/assets/71845777/278e0e67-f687-4ad6-97e8-d5871d34c523)

2023-11-29 22:22 UTC, zierbeek commented
[Uploading mealie_2023.11.10.14.35.55.zip…]()

2023-11-30 02:50 UTC, michael-genson commented
Whelp, your backup broke several things. They seem fixed now, though to be honest I'm not quite sure why. I built the SQL manually and ran some tests locally to make sure data was still intact. I'm going to send over the migrated db on Discord, if you can check to make sure it works that'd be great.

2023-12-03 22:10 UTC, hay-kot requested changes

2023-12-03 22:10 UTC, hay-kot commented on alembic/versions/2023-09-01-14.55.42_0341b154f79a_added_normalized_unit_and_food_names.py
> +                    f"UPDATE {IngredientUnitModel.__tablename__} SET name_normalized='{IngredientUnitModel.normalize(unit.name)}' WHERE id='{unit.id}'"
FYI, you either need to use a parameterized query or properly escape the text to ensure it doesn't break stuff. 

See #2783 for an example of the problem.

2023-12-03 22:10 UTC, hay-kot commented on alembic/versions/2023-09-01-14.55.42_0341b154f79a_added_normalized_unit_and_food_names.py
> +                    f"UPDATE {IngredientUnitModel.__tablename__} SET abbreviation_normalized='{IngredientUnitModel.normalize(unit.abbreviation)}' WHERE id='{unit.id}'"
See above

2023-12-03 22:10 UTC, hay-kot commented on alembic/versions/2023-09-01-14.55.42_0341b154f79a_added_normalized_unit_and_food_names.py
> +                    f"UPDATE {IngredientFoodModel.__tablename__} SET name_normalized='{IngredientFoodModel.normalize(food.name)}' WHERE id='{food.id}'"
See above

2023-12-03 22:10 UTC, hay-kot commented on alembic/versions/2023-10-04-14.29.26_dded3119c1fe_added_unique_constraints.py
> +    session.execute(sa.text(f"DELETE FROM {IngredientFoodModel.__tablename__} WHERE id='{dupe_food_id}'"))
See above

2023-12-03 22:10 UTC, hay-kot commented on alembic/versions/2023-10-04-14.29.26_dded3119c1fe_added_unique_constraints.py
> +    session.execute(sa.text(f"DELETE FROM {IngredientUnitModel.__tablename__} WHERE id='{dupe_unit_id}'"))
See above

2023-12-03 22:10 UTC, hay-kot commented on alembic/versions/2023-10-04-14.29.26_dded3119c1fe_added_unique_constraints.py
> +    session.execute(sa.text(f"DELETE FROM {MultiPurposeLabel.__tablename__} WHERE id='{dupe_label_id}'"))
See above

2023-12-04 14:55 UTC, michael-genson commented on alembic/versions/2023-09-01-14.55.42_0341b154f79a_added_normalized_unit_and_food_names.py
> +                    f"UPDATE {IngredientUnitModel.__tablename__} SET name_normalized='{IngredientUnitModel.normalize(unit.name)}' WHERE id='{unit.id}'"
I thought the normalize function we're running is supposed to strip all special characters from the string, but I guess it's not taking apostrophes out. That might be a problem for searches.

Either way we should be doing it regardless, so I'll go ahead and add that, thanks!

2023-12-04 19:15 UTC, hay-kot commented on alembic/versions/2023-09-01-14.55.42_0341b154f79a_added_normalized_unit_and_food_names.py
> +                    f"UPDATE {IngredientUnitModel.__tablename__} SET name_normalized=:name_normalized WHERE id=:id"
Do these substitutions work in both Postgres and SQL? I can't remember if they are db agnostic or not.

2023-12-04 19:21 UTC, michael-genson commented on alembic/versions/2023-09-01-14.55.42_0341b154f79a_added_normalized_unit_and_food_names.py
> +                    f"UPDATE {IngredientUnitModel.__tablename__} SET name_normalized=:name_normalized WHERE id=:id"
It looks like it works in Postgres: https://www.postgresql.org/docs/current/app-psql.html#APP-PSQL-INTERPOLATION

This stackoverflow answer says it should work with psycopg2 (which we use, I'm pretty sure): https://stackoverflow.com/a/39414254

And it definitely works in SQLite (I tested it locally but also: https://www.sqlite.org/c3ref/bind_blob.html)

2023-12-04 19:23 UTC, michael-genson commented on alembic/versions/2023-09-01-14.55.42_0341b154f79a_added_normalized_unit_and_food_names.py
> +                    f"UPDATE {IngredientUnitModel.__tablename__} SET name_normalized=:name_normalized WHERE id=:id"
Although if someone can verify on postgres that'd be great

2023-12-04 21:08 UTC, michael-genson commented
I had two different sqlite formats in my test data - one had UUIDs with dashes, one didn't. I resolved the ambiguity by changing the select statement to just give me the raw DB value, rather than trying to coerce things. Both of my test dbs were successful with this change

2023-12-06 18:05 UTC, hay-kot approved these changes
LGTM, will leave it up to you to merge 🚀

2023-12-06 18:37 UTC, merged