fix: Foreign Key Violations During Backup Restore
mealie-recipes/mealie pull request #2986
Opened 2024-01-13 21:19 UTC by michael-genson

## What type of PR is this?

_(REQUIRED)_

- bug

## What this PR does / why we need it:

_(REQUIRED)_

WIP, see https://github.com/mealie-recipes/mealie/issues/2499 and https://github.com/mealie-recipes/mealie/issues/2985

## Which issue(s) this PR fixes:

_(REQUIRED)_

WIP

2024-01-15 00:22 UTC, michael-genson commented
I manually confirmed the data locally looks correct. The number of recipes matches, the number of users matches, and the expected invalid foreign keys are missing.

2024-01-15 13:52 UTC, hay-kot requested changes
This is so much more simple than what I tried to do 10/10

2024-01-15 13:52 UTC, hay-kot commented on mealie/services/backups_v2/alchemy_exporter.py
> +                    continue
can we add some warning logs in here to indicate that we're dropping data?

2024-01-16 21:54 UTC, hay-kot approved these changes

2024-01-16 22:12 UTC, merged