feat: sort by labels in shopping list copy if labels toggled
mealie-recipes/mealie pull request #3226
Opened 2024-02-27 09:35 UTC by ollywelch

## What type of PR is this?

- feature

## What this PR does / why we need it:

This is a simple quality of life feature when copying shopping lists. Currently the lists always get copied in the order that is displayed when label sorting is off. So, when you toggle label sorting on, the copy function ends up copying in a different order to what is displayed. This change deals with the case when label sorting is on.

### Updates
- Updated the `copyListItems` function to unpack the values of the `itemsByLabel` mapping into the `items` to copy if label sorting is toggled on. Otherwise, it will have the same behaviour as before. 

## Which issue(s) this PR fixes:

No issues fixed.

## Special notes for your reviewer:

Go easy, not touched Vue before now :)

Also not sure if I need an issue creating for this, can create one and amend my commit msg to include it if needed.

## Testing

Ran the UI, made a shopping list with labels, then checked the copy output with label sorting toggled on and off.

2024-02-27 10:53 UTC, ollywelch commented
Actually discovered another issue while testing this, looks like the copy function is using the "display" property of the shopping list item which is always coming back blank - this is only an issue in the nightly build and not latest so must be a recent API change

2024-02-27 11:11 UTC, ollywelch commented
Raised https://github.com/mealie-recipes/mealie/issues/3227, will see if I can also fix this in my PR

2024-02-27 14:56 UTC, michael-genson commented
I haven't had the chance to fully test it out yet, but generally looks good! I went ahead and fixed that `post_validate` issue by renaming all the `post_validate` methods (I probably should've done that originally.

I should be able to take a closer look at this later today

2024-02-27 15:15 UTC, michael-genson commented
Would it make sense to also add the labels into the copied shopping list? I feel like if you want to keep them in label order, you probably also want the labels. Something like:

[Produce]
apples
bananas

[Meat]
1 lb chicken thighs

etc. I think we should at least have it in the markdown copy mode, though I'd argue you'd want it in the plaintext one too. I'm thinking something like this: https://github.com/mealie-recipes/mealie/pull/3032

2024-02-27 17:10 UTC, ollywelch commented
Nice one with just renaming the methods, that's a bit neater than calling the same `post_validate` method from the super class :+1: 

With copying the headings, I think you're right. I've had to re-engineer it and not use the `copyMarkdownCheckList` function, rather just use the `copyPlain` function regardless and do the markdown formatting up front. But have tested and it works well

2024-02-27 22:20 UTC, michael-genson commented
One small change and I think this is good to go. Thanks!

2024-02-28 18:10 UTC, michael-genson requested changes
Sorry, I just realized I left this as pending!

2024-02-28 18:10 UTC, michael-genson commented on frontend/pages/shopping-lists/_id.vue
> +          text.push(formatCopiedLabelHeading(copyType, label))
Can we add an empty line before each header? Unless it's the first header. So it renders like this:

```
[Label 1]
- [ ] item 1
- [ ] item 2

[Label 2]
- [ ] item 3
- [ ] item 4
```

But skip the first index, so something like:

```js
Object.entries(itemsByLabel.value).forEach(([label, items], idx) => {
  if (idx) {
    text.push("");
  }
  ...
}
```

2024-02-28 20:58 UTC, ollywelch commented on frontend/pages/shopping-lists/_id.vue
> +          text.push(formatCopiedLabelHeading(copyType, label))
Just made the update, I initially tried this yesterday but couldn't understand why I was getting two blank lines by pushing `"\n"` to the array :facepalm: 

Thanks for the guidance :smile:

2024-02-28 22:00 UTC, michael-genson approved these changes
Looks great, thank you!

2024-02-28 22:06 UTC, merged