feat: Recipe Instructions, add buttons for move to top or bottom
mealie-recipes/mealie pull request #3232
Opened 2024-02-28 08:14 UTC by boc-the-git

## What type of PR is this?

- feature

## What this PR does / why we need it:

Adds buttons to the recipe instructions to "move to top" or "move to bottom". When you've got 20 steps in a recipe and need to move things around, drag and drop can get very tedious!
Also introduces some dividers into the menu.

Before:
![image](https://github.com/mealie-recipes/mealie/assets/3479092/1b029690-a700-492c-818a-5c4f5d5bc4e1) 

After:
![image](https://github.com/mealie-recipes/mealie/assets/3479092/1890f356-ed62-4b9f-bc40-a53bd9627788)

## Which issue(s) this PR fixes:

None.

## Testing

Manual.

2024-02-28 18:10 UTC, michael-genson requested changes

2024-02-28 18:10 UTC, michael-genson commented on frontend/components/global/BaseButtonGroup.vue
> +            <v-divider v-if="child.divider" :key="`divider-${idx}`" class="my-1"></v-divider>
Would we be able to switch the component to put a divider on top, instead of on bottom? Only for consistency, because I know there are other components we have that behave that way

2024-03-01 09:08 UTC, boc-the-git commented on frontend/components/global/BaseButtonGroup.vue
> +            <v-divider v-if="child.divider" :key="`divider-${idx}`" class="my-1"></v-divider>
@michael-genson just confirming as mentioned on Discord that this is an area where we already don't have consistency. A couple examples where the divider is on the bottom (which I had used as my basis):

https://github.com/mealie-recipes/mealie/blob/a475afd570bddde1e1dda20f68942f794a80d96b/frontend/components/global/BaseOverflowButton.vue#L23

https://github.com/mealie-recipes/mealie/blob/a475afd570bddde1e1dda20f68942f794a80d96b/frontend/pages/register/index.vue#L227

2024-03-01 17:15 UTC, michael-genson commented on frontend/components/global/BaseButtonGroup.vue
> +            <v-divider v-if="child.divider" :key="`divider-${idx}`" class="my-1"></v-divider>
Thanks for taking a look!

2024-03-03 22:34 UTC, michael-genson approved these changes

2024-03-03 22:41 UTC, merged