security: gh security recs
mealie-recipes/mealie pull request #3368
Opened 2024-03-24 19:54 UTC by hay-kot

## What type of PR is this?

_(REQUIRED)_

- bug
- cleanup
- documentation
- feature

## What this PR does / why we need it:

_(REQUIRED)_

## Which issue(s) this PR fixes:

_(REQUIRED)_

## Special notes for your reviewer:

_(fill-in or delete this section)_

## Testing

_(fill-in or delete this section)_

2024-03-26 11:33 UTC, boc-the-git requested changes
The code changes all look good.
In testing the happy path, everything went well (i.e. I can still import recipes and images from legitimate internet sites.

In testing the negative path (trying to access things on my internal network), things came unstuck.

This first series of images is when accessing my Vikunja instance via the URL/reverse proxy (note I installed ping in the dev container to confirm what it's resolving to):
![image](https://github.com/mealie-recipes/mealie/assets/3479092/2e497b5e-839d-41cc-87f0-92a182729458)
![image](https://github.com/mealie-recipes/mealie/assets/3479092/b5e9301b-d236-4d55-a983-822cbb3b5a33)
![image](https://github.com/mealie-recipes/mealie/assets/3479092/22f64df7-383b-4aab-a517-ca2360990d49)

Then for a further test, I popped the IP/port in directly, avoiding the reverse proxy and any DNS resolution:
![image](https://github.com/mealie-recipes/mealie/assets/3479092/ba26aa76-5c91-4819-a6b3-bcd9f6017ff3)

@hay-kot I'm interested in whether you can replicate this scenario.

I dug a bit deeper, and wanted to get some evidence of what was happening, which this code change and error message shows.. effectively the IP is `None`, rather than `192.168.x.y` as I'd expect.
![image](https://github.com/mealie-recipes/mealie/assets/3479092/99e59e29-f27e-48d1-b24f-062a64396b18)

2024-03-28 11:05 UTC, p0lycarpio commented
Along the same lines as the `ALLOW_SIGNUP` variable which was set to `False`, I suggest setting all groups to private by default when they are created. This is an additional security measure and also when using Mealie for the first time the user would be redirected to the login/welcome page instead of the empty group.
What is your opinion ?

The change would be made in the [group_preferences.py](https://github.com/mealie-recipes/mealie/blob/7f596c653bdeaaee64efd5c6ec5f5f0a3108c2f4/mealie/schema/group/group_preferences.py#L9) schema. I don't know the impacts though.

2024-03-28 11:21 UTC, boc-the-git commented
@p0lycarpio do you want to raise a feature request for that (or discuss it on Discord)?
We wouldn't likely tackle that under this PR.

That's more a _privacy issue_ than a _security issue_, if you take my meaning.
I don't have strong feelings on it one way or the other; other people might.

2024-04-01 01:57 UTC, hay-kot commented
@boc-the-git should be good now. Thanks to some folks on discord it's 99% less bad too!

2024-04-01 09:04 UTC, boc-the-git commented on mealie/pkgs/safehttp/transport.py
> +            if len(netloc_parts) > 1:  # netloc of username:password@hostname:port not supported
The check here doesn't align with the comment.. should this be checking for `... > 2`?
I won't stop this delaying a merge, but will circle back to it, via Discord.

2024-04-01 09:04 UTC, boc-the-git commented on mealie/pkgs/safehttp/transport.py
> +                raise InvalidDomainError(f"unsupported request format: {request.url} -> {ip}")
The `ip` variable has never been set. Assume that's unintended.

2024-04-01 09:04 UTC, boc-the-git commented on mealie/pkgs/safehttp/transport.py
> +            if len(netloc_parts) > 1:  # netloc of username:password@hostname:port not supported
`... > 1` will always be true, except in some weird scenario where `:` was the first or last character of `netloc` (and tbh I'm not certain what happens in that scenario)

2024-04-01 09:04 UTC, boc-the-git commented on mealie/pkgs/safehttp/transport.py
> +                    self._log.debug(f"failed to parse ip for {netloc=} falling back to domain resolution")
I'm not familiar with how `{netloc=}` is being used here.. assuming the `=` is a typo

2024-04-01 09:15 UTC, boc-the-git commented on mealie/pkgs/safehttp/transport.py
> +                    self._log.debug(f"failed to parse ip for {netloc=} falling back to domain resolution")
From python.org..
![image](https://github.com/mealie-recipes/mealie/assets/3479092/ce30e616-3624-445a-801b-612821be7557)

2024-04-01 09:33 UTC, boc-the-git commented on mealie/pkgs/safehttp/transport.py
> -            if len(netloc_parts) > 1:  # netloc of username:password@hostname:port not supported
@hay-kot see this log.. showing that even when `user:pass` is included in the url, it was being stripped out before getting to this netloc variable. Thus, the check on parts is irrelevant here.

![image](https://github.com/mealie-recipes/mealie/assets/3479092/49f3101b-c775-4eb4-a534-cbcfca795f9e)

2024-04-01 09:35 UTC, boc-the-git approved these changes

2024-04-01 09:36 UTC, boc-the-git commented
@hay-kot this has my blessing, but note I had to make a fix. Please review, and merge/release as desired.

2024-04-01 10:49 UTC, tba-code commented on mealie/pkgs/safehttp/transport.py
> +            if len(netloc_parts) > 1:  # netloc of username:password@hostname:port not supported
It was a typo.

2024-04-02 15:04 UTC, merged