docs: add possible log levels
mealie-recipes/mealie pull request #3638
Opened 2024-05-23 11:24 UTC by DennisGaida

## What type of PR is this?

- documentation

## What this PR does / why we need it:

Found the documentation here: https://www.uvicorn.org/settings/#logging with the possible logging values (tried `WARN` only to figure out it needs to be `warning` or `WARNING`).

## Which issue(s) this PR fixes:
none

2024-05-31 22:05 UTC, michael-genson requested changes

2024-05-31 22:05 UTC, michael-genson commented on docs/docs/documentation/getting-started/installation/backend-config.md
> +| LOG_LEVEL                     |         info          | logging level (e.g. critical, error, warning, info, debug, trace)                   |
I don't think Python actually supports "trace" out of the box: https://docs.python.org/3/library/logging.html#levels

```suggestion
| LOG_LEVEL                     |         info          | logging level (e.g. critical, error, warning, info, debug)                          |
```

2024-06-01 17:25 UTC, DennisGaida commented on docs/docs/documentation/getting-started/installation/backend-config.md
> +| LOG_LEVEL                     |         info          | logging level (e.g. critical, error, warning, info, debug, trace)                   |
That may be so, but as stated in the original post including URL the Uvicorn library is used for logging which includes those levels.

2024-06-01 17:26 UTC, michael-genson commented on docs/docs/documentation/getting-started/installation/backend-config.md
> +| LOG_LEVEL                     |         info          | logging level (e.g. critical, error, warning, info, debug, trace)                   |
Wow I'm blind, thanks!

2024-06-01 17:28 UTC, michael-genson approved these changes, later dismissed

2024-06-01 21:11 UTC, boc-the-git approved these changes

2024-06-01 21:11 UTC, merged