chore(l10n): New Crowdin updates
mealie-recipes/mealie pull request #3738
Opened 2024-06-15 22:16 UTC by hay-kot

2024-06-15 22:44 UTC, boc-the-git requested changes
Just gonna block this temporarily..

I don't normally look at the detail of translations, but I can't understand why cup is being translated to "US cup"

2024-06-15 22:48 UTC, Kuchenpirat submitted a review, later dismissed

2024-06-20 11:49 UTC, boc-the-git commented
I will follow up on this in the coming days.. didn't intend my blocking of the en-gb to hold up all translations, but I guess that's a by product of how the crowding integration works.

2024-06-21 10:02 UTC, boc-the-git approved these changes

2024-06-21 10:09 UTC, merged