feat: PWA Additions
mealie-recipes/mealie pull request #3896
Opened 2024-07-15 18:46 UTC by Choromanski

## What type of PR is this?

- bug (Warnings in Chrome Dev Tools)
- feature

## What this PR does / why we need it:

This PR adds PWA Manifest members to make the application more useable across different platforms.

## Special notes for your reviewer:

Open to and encourage feedback on all manifest members updated.

## Testing

_(fill-in or delete this section)_

## Changes
### [Shortcut Icons](https://web.dev/articles/app-shortcuts#define_app_shortcuts_in_the_web_app_manifest):
Resized them and was required to have one that was 96x96 to resolve icon warnings in Chrome Dev Tools
![image](https://github.com/user-attachments/assets/0b198e8b-4fe5-4e71-ae48-a22e0456cfb7)
_Note: Documentation says that PNGs are preferred_

### [scope](https://developer.mozilla.org/en-US/docs/Web/Manifest/scope): `"/"`
Sets the scope of the application

### [dir](https://www.w3.org/TR/appmanifest/#dir-member): `"auto"`
Sets the text direction - Set to auto to allow support of both right to left and left to right
_Note: Since the lang is set to "en" this could probably be set to "ltr" but I can't verify that._

### [id](https://developer.mozilla.org/en-US/docs/Web/Manifest/id): `"mealie"`
Unique identifier for the PWA 

### [display_override](https://developer.mozilla.org/en-US/docs/Web/Manifest/display_override); `["standalone","minimal-ui","browser","window-controls-overlay"]`
Sets display priority

### [prefer_related_applications](https://developer.mozilla.org/en-US/docs/Web/Manifest/prefer_related_applications): `false`
If applications in the [related_applications](https://developer.mozilla.org/en-US/docs/Web/Manifest/related_applications) section should be preferred over PWA.
Currently no official non-web applications exist but if one is developed in the future is should be listed in `related_applications` and this should be set to `true`

### [handle_links](https://github.com/WICG/pwa-url-handler/blob/main/handle_links/explainer.md): `"preferred"`:
In-scope links should be opened within the installed PWA

### [orientation](https://developer.mozilla.org/en-US/docs/Web/Manifest/orientation): `"any"`
Default orientation of the application

### [categories](https://developer.mozilla.org/en-US/docs/Web/Manifest/categories): `["food"]`
Categories the application belongs to

### [launch_handler](https://developer.mozilla.org/en-US/docs/Web/API/Launch_Handler_API): `{"client_mode": ["focus-existing", "auto"]}`
How the application is launched

### [edge_side_panel](https://learn.microsoft.com/en-us/microsoft-edge/progressive-web-apps-chromium/how-to/sidebar): `{"preferred_width": 400}`
The preferred width when launching the PWA in an Edge side panel

2024-07-16 17:57 UTC, Kuchenpirat requested changes
Hey thanks for the work on this 😊

Before we can get to reviewing this. 
Your Indentation setting is set to a different value than two spaces. Please use this for all code regarding mealie. 

See the changes in `frontend/nuxt.config.js` as example

2024-07-16 20:21 UTC, Choromanski commented
> Hey thanks for the work on this 😊
> 
> Before we can get to reviewing this. Your Indentation setting is set to a different value than two spaces. Please use this for all code regarding mealie.
> 
> See the changes in `frontend/nuxt.config.js` as example

I resolved the spacing issue, sorry about that.

2024-07-17 06:57 UTC, Kuchenpirat commented
Thanks for the quick fix.
Looks all pretty good and your documentation makes is pretty easy to understand what is going on 👍

One thing. If you are already in there, would you be able to update the mealie icons to no longer include the white background? That would make it more consistent with the rest of the icons.

2024-07-17 14:32 UTC, Choromanski commented
I just went ahead and added some screenshots I made to resolve 2 of the warnings in the dev console:

Before:
![image](https://github.com/user-attachments/assets/fafd4abf-dfdc-4aef-aa65-2dbf127b686d)

After:
![image](https://github.com/user-attachments/assets/2b1a8426-3cd0-4bd6-a8a1-63fda3462eba)

This also lets us use the [Richer Install UI](https://web.dev/patterns/web-apps/richer-install-ui):

Desktop: 
<img width="226" alt="image" src="https://github.com/user-attachments/assets/6fd16e92-9b04-4454-ab5d-dd7d61d6fca9">

Mobile:
<img width="360" alt="image" src="https://github.com/user-attachments/assets/50c87069-16c6-4ce3-9c8b-605645c2165d">

2024-07-17 14:35 UTC, Choromanski commented
> Thanks for the quick fix. Looks all pretty good and your documentation makes is pretty easy to understand what is going on 👍
> 
> One thing. If you are already in there, would you be able to update the mealie icons to no longer include the white background? That would make it more consistent with the rest of the icons.

Do we have the original vector image anywhere? I tried working on the PNG for an hour and couldn't make it look good with my below average photo editing skills.

2024-07-17 17:26 UTC, Kuchenpirat commented
> Do we have the original vector image anywhere? I tried working on the PNG for an hour and couldn't make it look good with my below average photo editing skills.

oh i thought there was an svg version of that in the frontend, but apparently i was wrong and there is just the white background version. I have posted the svg code bellow, feel free to come back to me if you need anything more. 

```
<svg style="width:100px;height:100px" viewBox="0 0 24 24">
    <path fill="currentColor" d="M8.1,13.34L3.91,9.16C2.35,7.59 2.35,5.06 3.91,3.5L10.93,10.5L8.1,13.34M13.41,13L20.29,19.88L18.88,21.29L12,14.41L5.12,21.29L3.71,19.88L13.36,10.22L13.16,10C12.38,9.23 12.38,7.97 13.16,7.19L17.5,2.82L18.43,3.74L15.19,7L16.15,7.94L19.39,4.69L20.31,5.61L17.06,8.85L18,9.81L21.26,6.56L22.18,7.5L17.81,11.84C17.03,12.62 15.77,12.62 15,11.84L14.78,11.64L13.41,13Z" />
</svg>
```

2024-07-17 18:04 UTC, Choromanski commented
> > Do we have the original vector image anywhere? I tried working on the PNG for an hour and couldn't make it look good with my below average photo editing skills.
> 
> oh i thought there was an svg version of that in the frontend, but apparently i was wrong and there is just the white background version. I have posted the svg code bellow, feel free to come back to me if you need anything more.
> 
> ```
> <svg style="width:100px;height:100px" viewBox="0 0 24 24">
>     <path fill="currentColor" d="M8.1,13.34L3.91,9.16C2.35,7.59 2.35,5.06 3.91,3.5L10.93,10.5L8.1,13.34M13.41,13L20.29,19.88L18.88,21.29L12,14.41L5.12,21.29L3.71,19.88L13.36,10.22L13.16,10C12.38,9.23 12.38,7.97 13.16,7.19L17.5,2.82L18.43,3.74L15.19,7L16.15,7.94L19.39,4.69L20.31,5.61L17.06,8.85L18,9.81L21.26,6.56L22.18,7.5L17.81,11.84C17.03,12.62 15.77,12.62 15,11.84L14.78,11.64L13.41,13Z" />
> </svg>
> ```

Just pushed them, let me know what you think.

2024-07-22 07:09 UTC, Kuchenpirat commented
Sorry it took me so long to come back to this. 
I have found that if i reinstall the pwa on windows again the shortcuts are no longer added. I don't see a reason to why that would be, but maybe you could take a look at that. 

| **OLD** (with Shortcuts) | **NEW** (Shortcuts missing) |
| --- | --- |
| ![image](https://github.com/user-attachments/assets/9ba5fbcd-c950-4c2e-a677-20a13c66fd02) | ![image](https://github.com/user-attachments/assets/c23266a7-2a8f-4285-9786-2102817be2c6) |

2024-07-22 16:54 UTC, Choromanski commented
I am still seeing all the shortcuts: 
![image](https://github.com/user-attachments/assets/cc1774cc-4e0d-4036-b893-a74e6c6d79d4)

I know that pwa manifests are generally only rechecked by the browser once every 24 hours or so.

Could you try running it on a different port (just to force the browser to recheck the manifest) and reinstalling the PWA?

2024-07-22 17:38 UTC, Kuchenpirat commented
Thanks for the information. 👍

This might be a me issue then. I did try installing via a different port with the same result. 
I will do some investigating tomorrow and try a different machine to see if i can reproduce it somewhere else.

2024-07-23 12:10 UTC, Kuchenpirat commented
I tried again today with two different machines, with different browsers and launching nuxt on different ports with the same results. Now i am out of computers and none the wiser why it would show up for you and not for me 🧐

2024-07-23 14:31 UTC, Choromanski commented
> I tried again today with two different machines, with different browsers and launching nuxt on different ports with the same results. Now i am out of computers and none the wiser why it would show up for you and not for me 🧐

Do you have any errors in Chrome Dev Tools  under Application > Manifest?

PWAs require HTTPS but I've noticed HTTP works if you use localhost. Is it possible you are not using localhost and missing HTTPS?

2024-07-23 15:04 UTC, Kuchenpirat approved these changes
Ok, i figured it out and it was pretty much me being uninformed. I actually did not install as PWA but as an chrome app or however those things are called. 
Long story short. Everything shows up correctly including the shortcuts. 

Thanks for your work on this and helping me with the review! 🚀

2024-07-23 15:04 UTC, merged

2024-07-23 15:05 UTC, Choromanski commented
> Ok, i figured it out and it was pretty much me being uninformed. I actually did not install as PWA but as an chrome app or however those things are called. 
> Long story short. Everything shows up correctly including the shortcuts. 
> 
> Thanks for your work on this and helping me with the review! 🚀

Glad I could help!

2024-07-31 11:01 UTC, julianwachholz commented on frontend/nuxt.config.js
> +      id: "mealie",
FWIW this defaults to the PWA's host at time of installation. Using a fixed value in the manifest will prevent users from installing potentially multiple different Mealie instances. Not that this is a common use case but worth mentioning nontheless.

https://developer.chrome.com/docs/capabilities/pwa-manifest-id

2024-07-31 11:31 UTC, felixschndr commented
> ![image](https://private-user-images.githubusercontent.com/3665694/348854872-7cd3dfbc-a877-4da5-96e8-a1eb16a624b2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0MjU1MTUsIm5iZiI6MTcyMjQyNTIxNSwicGF0aCI6Ii8zNjY1Njk0LzM0ODg1NDg3Mi03Y2QzZGZiYy1hODc3LTRkYTUtOTZlOC1hMWViMTZhNjI0YjIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDczMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MzFUMTEyNjU1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZGE3ZDA5NWJmNDAxZjhmOTQ2NmE1NTNkMmU4Yzk2YmJjYTA1ODY3OTJkMzI0ZDNiNDVkNjFlZGNkMTVlMmQ4NCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.8vLVY4jvnWUkHocZwrWqvUo6bkqYJFJbbCy8yk7y9M4)

Just a quick question: How did you change the color of your interface from orange to pink?

2024-07-31 14:30 UTC, Choromanski commented
You have to update the THEME variables: https://docs.mealie.io/documentation/getting-started/installation/backend-config/