Fix: Homepage icon and text update
mealie-recipes/mealie pull request #3922
Opened 2024-07-21 21:21 UTC by tyme-dev

## What type of PR is this?

_(REQUIRED)_

- bug
## What this PR does / why we need it:
_(REQUIRED)_

Updates text  / icon on sidebar and recipe explorer page to better fit homepage context.

## Changes

- Changes Icon on sidebar for homepage and on the homepage itself from mdiMagnify to mdisilverwareFork
- Update text on sidebar for homepage and on the homepage itself to say "Recipes" instead of "Search" or "Results" 

Before: 
![image](https://github.com/user-attachments/assets/d0d3dc77-0d33-4c5a-8964-2fdccc0bd071)

After: 
![image](https://github.com/user-attachments/assets/6a083e1a-cf6e-4096-83b8-653f9b026797)

## Which issue(s) this PR fixes:

_(REQUIRED)_
Fixes #3815

2024-07-24 10:28 UTC, boc-the-git requested changes
The only language file that should ever be modified directly is `en-US.json` - all other translations are handled via Crowdin.

2024-07-24 12:22 UTC, tyme-dev commented
@boc-the-git oh okay, thank you for the clarification, i've slimmed it down to a more reasonable 4 file changes :)

2024-07-25 11:24 UTC, boc-the-git requested changes
We already have general.recipes, so there's no real need to add a new "recipes" translation in. This has the added benefit of not needing people to go in and apply a new translation for it, it'll be in their language (assuming already translated) as soon as we merge this!

Otherwise, this change looks good and I'm happy to merge! Thanks :)

2024-07-25 11:24 UTC, boc-the-git commented on frontend/components/Domain/Recipe/RecipeExplorerPage.vue
> +        :title="$tc('search.recipes')"
```suggestion
        :title="$tc('general.recipes')"
```

2024-07-25 11:24 UTC, boc-the-git commented on frontend/components/Layout/DefaultLayout.vue
> +          title: i18n.tc("sidebar.recipes"),
```suggestion
          title: i18n.tc("general.recipes"),
```

2024-07-25 11:24 UTC, boc-the-git commented on frontend/lang/messages/en-US.json
> +    "recipes": "Recipes"
```suggestion
    "no-results": "No results found"
```

2024-07-25 11:24 UTC, boc-the-git commented on frontend/lang/messages/en-US.json
> +    "recipes": "Recipes"
```suggestion
    "create-cookbook": "Create a new cookbook"
```

2024-07-25 11:32 UTC, tyme-dev commented
@boc-the-git updated to use general.recipes

2024-07-25 11:38 UTC, Kuchenpirat reviewed
i would like to see a different icon used here. I think the choosen icon is a bit small in contrast to the others. 

I would either suggest mdiSilverwareForkKnife or just the primary mealie icon

Bellow are screenshots for both options. 

| Primary | ForkKnife |
| --- | --- |
| ![image](https://github.com/user-attachments/assets/f6a24fbd-3174-4458-8b77-b4170d825e86) | ![image](https://github.com/user-attachments/assets/51c8c18f-82df-4672-936f-8d328b08f59b) |

2024-07-27 22:54 UTC, tyme-dev commented
> i would like to see a different icon used here. I think the choosen icon is a bit small in contrast to the others.
> 
> I would either suggest mdiSilverwareForkKnife or just the primary mealie icon
> 
> Bellow are screenshots for both options.
> Primary 	ForkKnife
> ![image](https://github.com/user-attachments/assets/f6a24fbd-3174-4458-8b77-b4170d825e86) 	![image](https://github.com/user-attachments/assets/51c8c18f-82df-4672-936f-8d328b08f59b)

my preferment would be for mdiSilverwareForkKnife. @boc-the-git thoughts?

2024-07-27 23:39 UTC, boc-the-git commented
> > i would like to see a different icon used here. I think the choosen icon is a bit small in contrast to the others.
> > I would either suggest mdiSilverwareForkKnife or just the primary mealie icon
> > Bellow are screenshots for both options.
> > Primary 	ForkKnife
> > ![image](https://private-user-images.githubusercontent.com/24235032/352091902-f6a24fbd-3174-4458-8b77-b4170d825e86.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIxMjM3OTEsIm5iZiI6MTcyMjEyMzQ5MSwicGF0aCI6Ii8yNDIzNTAzMi8zNTIwOTE5MDItZjZhMjRmYmQtMzE3NC00NDU4LThiNzctYjQxNzBkODI1ZTg2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI3VDIzMzgxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdlNjJkZWZiYzE3YTM1ZmIzNjc1ODJmZTU0MGUyNjg4MzcwM2UzMmJiNGYzMDU3N2Q3Zjg1ZDlkZWFmYjVkMDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.91IN_vBBz0iIpm_aK8uqgoJIN6Phax-4bHtf_QuHnyA) 	![image](https://private-user-images.githubusercontent.com/24235032/352092032-51c8c18f-82df-4672-936f-8d328b08f59b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIxMjM3OTEsIm5iZiI6MTcyMjEyMzQ5MSwicGF0aCI6Ii8yNDIzNTAzMi8zNTIwOTIwMzItNTFjOGMxOGYtODJkZi00NjcyLTkzNmYtOGQzMjhiMDhmNTliLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI3VDIzMzgxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYzMjFhNTBjODRmZTc4Y2MwOTk5ZDM4ZWY0YjBkNDIxYzM0YzA1M2UyZTc5MDhlODU2NTU2NzA4MWZmZGU1Y2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.717Px_pOhP9zUA5Nij-03YBn_ylRKv6JbQAscqVtjis)
> 
> my preferment would be for mdiSilverwareForkKnife. @boc-the-git thoughts?

I'm fine with that too. I think _not_ using the logo is not a bad thing here.

2024-07-28 00:24 UTC, tyme-dev commented
@boc-the-git updated to use mdiSilverwareForkKnife.

2024-07-28 02:04 UTC, boc-the-git approved these changes

2024-07-28 02:04 UTC, boc-the-git commented
Thanks @tyme-dev !

2024-07-28 04:08 UTC, merged

2024-07-28 06:31 UTC, Kuchenpirat commented
Thanks @tyme-dev for your work on this. Always nice to see new contributors submit a PR! 😊

2024-08-01 18:12 UTC, simgunz commented
Thanks @tyme-dev. The UI is way more clean and understandable now.