Added extended Home Assistant example in documentation
mealie-recipes/mealie pull request #4031
Opened 2024-08-13 16:30 UTC by Wetzel402

## What type of PR is this?

_(REQUIRED)_

- documentation
Added extended Home Assistant example

2024-08-22 15:24 UTC, michael-genson requested changes
I can't suggest changes on line 27 and 39, but could you also update those from `.../groups/mealplans...` to `.../households/mealplans...`? The new households PR changes those endpoints

2024-08-22 15:24 UTC, michael-genson commented on docs/docs/documentation/community-guide/home-assistant.md
> +  - resource_template: http://mealie:9000/api/groups/mealplans?start_date={{ now().strftime('%Y-%m-%d') }}&page=1&perPage=5&orderBy=date&orderDirection=asc
```suggestion
  - resource_template: http://mealie:9000/api/households/mealplans?start_date={{ now().strftime('%Y-%m-%d') }}&page=1&perPage=5&orderBy=date&orderDirection=asc
```

2024-08-22 15:24 UTC, joostlek commented on docs/docs/documentation/community-guide/home-assistant.md
> +```yaml
Should we change this to using the integration?

2024-08-23 17:11 UTC, Wetzel402 commented on docs/docs/documentation/community-guide/home-assistant.md
> +```yaml
I think the wording from the previous users is accurate and I'm just reusing it.  We are creating REST sensors for HA.  In HA integration typically means something more advanced though `sensor.rest` is technically an integration too. 

https://www.home-assistant.io/integrations/sensor.rest/
https://www.home-assistant.io/integrations

2024-08-23 18:12 UTC, joostlek commented on docs/docs/documentation/community-guide/home-assistant.md
> +```yaml
Yes but I'm talking about using the mealie integration to communicate with Mealie.

2024-08-23 20:03 UTC, Wetzel402 commented on docs/docs/documentation/community-guide/home-assistant.md
> +```yaml
Is there a HACS integration?

2024-08-23 20:14 UTC, michael-genson commented on docs/docs/documentation/community-guide/home-assistant.md
> +```yaml
Mealie is an official integration now: https://www.home-assistant.io/integrations/mealie/

2024-08-23 20:51 UTC, Wetzel402 commented on docs/docs/documentation/community-guide/home-assistant.md
> +```yaml
Considering there is an official integration I may have to rewrite the documentation for this PR.  I will have to explore the integration.  As it stands now my PR doesn't use the integration at all but rather the API and REST sensors.

2024-08-24 05:48 UTC, joostlek commented on docs/docs/documentation/community-guide/home-assistant.md
> +```yaml
I did add services that you can use to request stuff and then use a template trigger to be able to create template entities from that response. It's a bit more complicated than having ready to go entities, but it is very flexible now

2024-08-26 16:06 UTC, closed without merging