feat:  Shopping list UI overhaul
mealie-recipes/mealie pull request #4077
Opened 2024-08-22 16:49 UTC by Wetzel402

## What type of PR is this?

- feature

## What this PR does / why we need it:

The shopping list UI seemed a bit complex.  This PR's goal is to...
1. Simplify the UI by moving buttons to an overflow menu in the upper corner
2. List items are in v-card now to help with readability
3. Each label now has it's own add button that should add to that label by default to speed up/simplify adding under that label. (in progress) 
4. Default to the label sorted view rather than the unsorted view (incomplete)

## Which issue(s) this PR fixes:

None

## Testing

Tested in dev container

2024-08-22 17:17 UTC, Kuchenpirat commented
Gonna leave some early feedback here. 
In my opinion putting the items in cards adds a lot of unnecessairy noise to the ui. 

I think its also more pronounced when not in dark mode, so additional screenshots bellow. 

| With Cards | Without Cards |
| ----- | ----- |
| ![image](https://github.com/user-attachments/assets/e0f63a90-350f-4f25-9c73-1f0441e42d4a)  |  ![image](https://github.com/user-attachments/assets/46ff4c0a-15da-4cc7-a48c-8fe0f26024dd) |

The look without them just looks way cleaner.

2024-08-22 17:24 UTC, Wetzel402 commented
> The look without them just looks way cleaner.

I agree especially with the divider per label

2024-09-15 11:36 UTC, boc-the-git commented
FYI @Wetzel402, this is failing CI, which is the reason I haven't spent any time to review it (and I imagine similar might be true for others)

2024-09-16 14:17 UTC, Wetzel402 commented
> FYI @Wetzel402, this is failing CI, which is the reason I haven't spent any time to review it (and I imagine similar might be true for others). Oh, and it's marked as a draft.

I removed the unused variable.  The PR is in draft due to the major UI changes.  @Kuchenpirat  was reviewing the changes and we may still make changes to the PR before it is incorporated fully into `mealie:next`.  There were also a few things I didn't fully finish working on due to my limited knowledge of `vue` and not knowing if the features would be fully approved or not.  I think we should wait for @Kuchenpirat's feedback and go from there.

2024-09-16 14:19 UTC, Kuchenpirat commented
Ah sorry was not aware this was blocked by me. Will take review tomorrow during the day👍

2024-09-16 21:25 UTC, Wetzel402 commented
> Ah sorry was not aware this was blocked by me. Will review tomorrow during the day👍

I wouldn't say blocked.  I just know you were looking at the UX changes based on our discord discussion.  Thanks!

2024-09-17 07:17 UTC, Kuchenpirat requested changes
Looking at all my comments i really suggest just sliming down this PR, focusing on the key elements while addressing the rest in separate PRs. This way, you'll have something merged quickly and can build on it, allowing us to review and discuss specific items more effectively instead of tackling such a broad PR.

I really like the general idea of cleaning up the shopping list interface, but some aspects still need work.

What is ready to go:
- The visual change of having labels over each category
- Wake lock

I'm happy to merge a PR with these updates, and we can address the rest in future PRs. 👍

2024-09-17 07:17 UTC, Kuchenpirat commented on frontend/components/Domain/ShoppingList/ShoppingListItem.vue
> +    const itemLabelCols = ref<string>(props.value.checked ? "auto" : props.showLabel ? "8" : "9");
This makes a lot more sense for long list items 👍

2024-09-17 07:17 UTC, Kuchenpirat commented on frontend/pages/group/data/labels.vue
> +        editLabel.value.color = "#757575";
Any particular reason you changed this?

2024-09-17 07:17 UTC, Kuchenpirat commented on frontend/pages/shopping-lists/_id.vue
> +            </v-col>
I think this needs some more work. 
It might be ok to hide a few things behind the three dot menue, but for some things it gets a bit to much. 
E.g. the Owner Settings are now: Three Dot ➡️ Menu ➡️ Settings

My suggestion would be to have that in a later PR, this needs to be a bit more fleshed out. 
The thing i am sure that makes sense to put in a three dot menu would be the owner settings menu. Im not too sure about the rest

2024-09-17 07:17 UTC, Kuchenpirat commented on frontend/pages/shopping-lists/_id.vue
> +            <!-- Create Item -->
i think it is clear that this needs to be polished quite a bit, but i really like the concept and think that this creation flow is the way to go 👍

2024-09-17 07:17 UTC, Kuchenpirat commented on frontend/pages/shopping-lists/_id.vue
> +      <!-- Menu dialog -->
This needs still some work. Having a button in a three dot menue that leads to a modal with further menue options is not the way to do it.

2024-09-17 07:17 UTC, Kuchenpirat commented on frontend/pages/shopping-lists/_id.vue
> +    </div>
Having the options for wake lock in the shoping list makes absolutely sense 👍😍

2024-09-19 16:17 UTC, Wetzel402 commented on frontend/pages/group/data/labels.vue
> +        editLabel.value.color = "#757575";
If I remember correctly the new label dividers made visibility poor on one of the themes so I made it a bit darker gray to compensate.  I would have to play with it to let you know for sure.

2024-09-19 16:28 UTC, Wetzel402 commented on frontend/pages/shopping-lists/_id.vue
> +            </v-col>
I will try to separate out the changes as you suggest and we can look at the three dot menu separately.

2024-09-19 18:55 UTC, Wetzel402 commented
> Looking at all my comments i really suggest just sliming down this PR, focusing on the key elements while addressing the rest in separate PRs. This way, you'll have something merged quickly and can build on it, allowing us to review and discuss specific items more effectively instead of tackling such a broad PR.
> 
> I really like the general idea of cleaning up the shopping list interface, but some aspects still need work.
> 
> What is ready to go:
> 
> * The visual change of having labels over each category
> * Wake lock
> 
> I'm happy to merge a PR with these updates, and we can address the rest in future PRs. 👍

PRs for these 2 changes:
https://github.com/mealie-recipes/mealie/pull/4235
https://github.com/mealie-recipes/mealie/pull/4236

2024-09-19 19:19 UTC, Wetzel402 commented on frontend/components/Domain/ShoppingList/ShoppingListItem.vue
> +    const itemLabelCols = ref<string>(props.value.checked ? "auto" : props.showLabel ? "8" : "9");
PR for this change...
https://github.com/mealie-recipes/mealie/pull/4237

2024-09-19 19:26 UTC, Wetzel402 commented
PR for defaulting to the label sorted view...
https://github.com/mealie-recipes/mealie/pull/4238

2024-09-25 17:14 UTC, Kuchenpirat commented
Will close this as this has been divided up on the following PRs: 
- #4236 
- #4244
- #4237 
- #4238 
- #4235 

The remaining features are not production ready yet. We are happy to get them in potential future PRs 👍

2024-09-25 17:14 UTC, closed without merging