docs: add keep screen alive entry
mealie-recipes/mealie pull request #4116
Opened 2024-08-28 19:55 UTC by paaff

## What type of PR is this?
Adding an entry to the documentation's FAQ section.

- documentation

## What this PR does / why we need it:

I've recently started using Mealie and came across the issue of not being able to find the Keep Screen Alive button. I began searching the documentation, code and discord and found that other's had mentioned why it usually didn't appear. Either not using HTTPS or not using a supported browser. That was also the case in my instance. :) 

So I thought, why not add to the FAQ in the event future new users wondered the same thing. 

## Which issue(s) this PR fixes:

No issues.

2024-08-28 20:59 UTC, boc-the-git commented
I believe there's also a known failure case on iOS. I'll suggest some wording when I get the chance, if no one beats me to it.

2024-09-06 14:25 UTC, michael-genson requested changes
Thanks for this! A few minor grammar/clarity things

2024-09-06 14:25 UTC, michael-genson commented on docs/docs/documentation/getting-started/faq.md
> +## Why is there no Keep Screen Alive button when I access a Mealie Recipe?
```suggestion
## Why is there no "Keep Screen Alive" button when I access a recipe?
```

2024-09-06 14:25 UTC, michael-genson commented on docs/docs/documentation/getting-started/faq.md
> +You've perhaps visited the Mealie Demo and noticed that it had a Keep Screen Alive button, but it doesn't show up in your own Mealie instance.
```suggestion
You've perhaps visited the Mealie Demo and noticed that it had a "Keep Screen Alive" button, but it doesn't show up in your own Mealie instance.
```

2024-09-06 14:25 UTC, michael-genson commented on docs/docs/documentation/getting-started/faq.md
> +There are typically two possible reasons for this.
```suggestion
There are typically two possible reasons for this:
```

2024-09-06 14:25 UTC, michael-genson commented on docs/docs/documentation/getting-started/faq.md
> +- You're accessing your Mealie instance without using HTTPS. The Wake Lock API is only available if HTTPS is used. Read more here: https://developer.mozilla.org/en-US/docs/Web/API/Screen_Wake_Lock_AP
```suggestion
1. You're accessing your Mealie instance without using HTTPS. The Wake Lock API is only available if HTTPS is used. Read more here: https://developer.mozilla.org/en-US/docs/Web/API/Screen_Wake_Lock_API
```

2024-09-06 14:25 UTC, michael-genson commented on docs/docs/documentation/getting-started/faq.md
> +- Or, you're accessing your Mealie instance on a browser which is not supported. You can test this here: https://vueuse.org/core/useWakeLock/#demo
```suggestion
2. You're accessing your Mealie instance on a browser which doesn't support the API. You can test this here: https://vueuse.org/core/useWakeLock/#demo
```

2024-09-06 18:40 UTC, paaff reviewed
Looks good to me, definitely an improvement. :)

2024-09-06 18:50 UTC, paaff commented
Yo @michael-genson - Kinda new in making PR's, committing the suggested changes and such. 
I hope I did it correctly, but if not, please let me know :)

2024-09-06 18:55 UTC, michael-genson approved these changes
Looks great, thank you!

2024-09-06 19:03 UTC, merged