docs: boolean value in docker-compose examples not deserializable in env variables
mealie-recipes/mealie pull request #4130
Opened 2024-08-31 13:12 UTC by ursuscamp

## What type of PR is this?

- documentation

## What this PR does / why we need it:

Booleans values in docker-compose environment variables are deserializable and results in an error like this

```
ERROR: The Compose file './docker-compose.yaml' is invalid because:
services.mealie.environment.ALLOW_SIGNUP contains false, which is an invalid type, it should be a string, number, or a null
```

## Which issue(s) this PR fixes:

N/A

2024-08-31 13:28 UTC, michael-genson commented
Are you using `docker compose` or `docker-compose`? The latter is deprecated.

Otherwise, make sure docker is up to date.

2024-09-06 14:30 UTC, michael-genson requested changes
Thanks! I noticed it works fine in mine without quotes, but I think it's because I use list syntax instead of map syntax? Maybe it's undefined behavior? Who knows, I can barely find docs about it.

Would we be able to use double quotes? Only because we already have the port in double quotes.

2024-09-11 22:37 UTC, hay-kot requested changes

2024-09-11 22:37 UTC, hay-kot commented on docs/docs/documentation/getting-started/installation/postgres.md
> +      ALLOW_SIGNUP: 'false'
```suggestion
      ALLOW_SIGNUP: "false"
```

2024-09-11 22:37 UTC, hay-kot commented on docs/docs/documentation/getting-started/installation/sqlite.md
> +      ALLOW_SIGNUP: 'false'
```suggestion
      ALLOW_SIGNUP: "false"
```

2024-09-11 22:38 UTC, hay-kot approved these changes

2024-09-11 22:41 UTC, michael-genson approved these changes

2024-09-11 22:47 UTC, merged