fix: Exclude additional sensitive information from mealie logs
mealie-recipes/mealie pull request #4218
Opened 2024-09-16 15:26 UTC by bigcat2014

## What type of PR is this?

_(REQUIRED)_
- bug
- cleanup

## What this PR does / why we need it:

_(REQUIRED)_
Add LDAP_QUERY_PASSWORD,  OIDC_CLIENT_ID, and OPENAI_API_KEY to the list of excluded settings when logging.

## Which issue(s) this PR fixes:

_(REQUIRED)_
Fixes #4217

## Testing
Run Mealie and view the logs, you should no longer see the above listed variables printed to the log on startup.

2024-09-16 19:08 UTC, cmintey commented
OIDC_CLIENT_ID is not sensitive

2024-09-18 06:04 UTC, boc-the-git requested changes
Per @cmintey: https://github.com/mealie-recipes/mealie/pull/4218#issuecomment-2353706720

2024-09-18 06:04 UTC, boc-the-git commented on mealie/app.py
> +                "OIDC_CLIENT_ID",
```suggestion
```

2024-09-21 21:59 UTC, boc-the-git approved these changes

2024-09-21 22:07 UTC, merged