feat: Shopping list UI overhaul - add wakelock
mealie-recipes/mealie pull request #4236
Opened 2024-09-19 18:53 UTC by Wetzel402

## What type of PR is this?

- feature

## What this PR does / why we need it:

- Add keep screen awake 
## Which issue(s) this PR fixes:

https://github.com/mealie-recipes/mealie/pull/4077
## Testing

Tested in dev container

2024-09-19 20:13 UTC, Kuchenpirat reviewed
Thanks for spliting all this up. Makes it super easy to review 😊👍
Since this is all the same code as on the recipe page, could you create a component that includes the switch as well as the functionality and just throw this component on both pages? 
Decreases duplicate code and makes the code of those pages a bit less convoluted.

2024-09-19 20:31 UTC, Wetzel402 commented
> Thanks for spliting all this up. Makes it super easy to review 😊👍 Since this is all the same code as on the recipe page, could you create a component that includes the switch as well as the functionality and just throw this component on both pages? Decreases duplicate code and makes the code of those pages a bit less convoluted

That makes sense.  It might take me a bit to figure that out since I'm new to `vue`.

2024-09-19 20:56 UTC, Kuchenpirat commented
No worries. If you want to tackle this have fun, but if this is just work for you i am happy to throw this together in 5 minutes and add this to this PR.

2024-09-19 21:43 UTC, Wetzel402 commented
> No worries. If you want to tackle this for fun all good and take your time, but if this is just work for you i am happy to throw this together in 5 minutes and add this to this PR.

Maybe I'm a masochist but I enjoy putting myself through learning new ways to code...haha

I've pushed the changes for your review.

2024-09-19 21:56 UTC, michael-genson requested changes
Check the files changed tab on GH; a few linter warnings got raised. I also added a few comments

2024-09-19 21:56 UTC, michael-genson commented on frontend/components/Domain/Recipe/RecipePage/RecipePage.vue
> +import Wakelock from "~/components/global/Wakelock.vue";
No need to import since you added it as a global component

2024-09-19 21:56 UTC, michael-genson commented on frontend/components/global/Wakelock.vue
> +<template>
You can name it something like `WakelockSwitch`

2024-09-19 21:58 UTC, michael-genson commented on frontend/components/global/Wakelock.vue
> +    setup(props, context) {
You can leave this empty if you're not using props/context

```suggestion
    setup() {
```

2024-09-22 09:29 UTC, Kuchenpirat submitted a review, later dismissed
Looks good to me 🚀
Thanks for your work on this!

Ah right, i missed the code warnings.

2024-09-23 14:54 UTC, michael-genson requested changes
There's still a few warnings to take care of; check out the "Files changed" tab on GH and scroll down and you'll see them

2024-09-26 17:19 UTC, Wetzel402 commented
> There's still a few warnings to take care of; check out the "Files changed" tab on GH and scroll down and you'll see them

Sorry for the delay.  PR should be ready now.

2024-09-27 06:48 UTC, Kuchenpirat commented
@Wetzel402 any reason you closed this?

2024-09-27 14:55 UTC, Wetzel402 commented
> @Wetzel402 any reason you closed this?

Sorry, I thought it had been merged already and was doing some pruning on my repository.

2024-09-28 14:58 UTC, Kuchenpirat approved these changes
Looks all good 👍

2024-09-28 15:07 UTC, michael-genson approved these changes

2024-09-28 15:16 UTC, merged

2024-10-02 11:58 UTC, boc-the-git commented
Thanks for this @Wetzel402; it was useful to me today! :)