feat: Shopping list UI overhaul - three dot menu
mealie-recipes/mealie pull request #4415
Opened 2024-10-22 15:23 UTC by Wetzel402

## What type of PR is this?

- feature

## What this PR does / why we need it:

Moved shopping list action bar into a three dot menu to clean up the UI/UX.

## Which issue(s) this PR fixes:

None

## Testing

Tested in docker container

2024-11-17 13:44 UTC, Kuchenpirat commented
This has been marked as draft for quite some time without progress, anything you need from us to get this over the finish line?

2024-11-18 15:21 UTC, Wetzel402 commented
> This has been marked as draft for quite some time without progress, anything you need from us to get this over the finish line?

I know there was some discussion among the core team regarding what should be in the menu vs what should be exposed as a separate button.  I posted in the Discord asking for feedback and then honestly forgot about it.

2024-11-26 07:11 UTC, Kuchenpirat reviewed
Ok, so I finally made some free time and looked at your proposal, I think it is a good idea to tidy up the interface, but I think putting absolutely everything is a bit too much.
So, I tried to move stuff around a bit and add it to its relevant places.

## Delete & Uncheck All Icon
The Delete icon (to delete all checked items) as well as the box to uncheck all items should be where the checked items are. Especially with the delete items people will assume that it deletes the shopping list instead of the checked items.
I’d suggest something like this:
![image](https://github.com/user-attachments/assets/52bb32bb-7861-4adf-b899-9209e3101622)

 
## Owner Menu
I would move the “owner” menu to the shopping lists overview page. I’d say it makes much more sense over there. 
Something like this should be pretty intuitive

![image](https://github.com/user-attachments/assets/1fd7dcea-d26e-4fd7-aa0d-2dc448b74a20)

 
## Copy & Check All
I'd think the copy and check all buttons are use pretty frequently so i would like them to not be hidden. I think a slimmed down version of the old Button Group is fine. 
![image](https://github.com/user-attachments/assets/952f24e9-3815-44f4-bef2-7f401ff54243)


## Remaing Buttons
The Rest of the Remaining Buttons should be moved to a three dot menu since those will not be used on a super regular basis and don't need to take up prime real estate. 
The result should look something like this which should be pretty clean.
The three dot menu contains `Toggle Label Sort`, `Reorder Labels` and `Manage Labels`

## Miscellaneous
I would also rename the button to the shopping lists overview to “All Lists” because it is not a back button since it does not go back where the user came from. 
The image on the top should be only shown on desktop view. On mobile it takes up to much of the most important space and will makes the top section look crammed. 

---

I hope you like where i am going with this. As always happy for feedback from you or the other members on the community. Always happy to have better ideas suggested.

2025-01-13 09:29 UTC, Kuchenpirat commented
hey @Wetzel402 any progress on this one?
Happy to lend a helping hand.

2025-01-14 15:14 UTC, Wetzel402 commented
> hey @Wetzel402 any progress on this one? Happy to lend a helping hand.

Sorry, between the holidays and work I haven't had any time to work on it.  I will try to find some time to work on this.

2025-01-15 21:59 UTC, Wetzel402 commented
This is ready for review and I love how it all came together.  So much cleaner.  Thanks!

2025-01-16 11:44 UTC, Kuchenpirat requested changes
Thanks for the quick work. 

There is one major problem with updating the shopping list owner. 
The list items are deleted if an api call is made (every time you click confirm on that dialog). You probably have to get the full list(including its items) and send that to the api instead of the summary that is used by the shoping list overview page. 
You probably can also skip the api call if the owner has not been updated. 

Besides that some minor comments for the first feedback round.

2025-01-16 11:44 UTC, Kuchenpirat commented on frontend/pages/shopping-lists/_id.vue
> +                  <v-menu offset-y>
Its pretty confusing that any item inside the three dot menu has the same icon, i would suggest either not using icons or we need to switch it up a little, otherwise there is no advantage in using icons.

2025-01-16 11:44 UTC, Kuchenpirat commented on frontend/pages/shopping-lists/_id.vue
> +            <v-col class="d-flex justify-end">
any reason to not use a BaseButtonGroup here?

2025-01-23 19:48 UTC, Wetzel402 commented
Hopefully this one is ready to pull now.

2025-01-24 09:55 UTC, Kuchenpirat requested changes
99% there, just a few nitpicky things that are mostly about naming stuff correctly.

2025-01-24 09:55 UTC, Kuchenpirat commented on frontend/pages/shopping-lists/index.vue
> +        :title="$t('general.settings')"
As this is no longer a general settings menu i would update the title.

2025-01-24 09:55 UTC, Kuchenpirat commented on frontend/pages/shopping-lists/index.vue
> +    const settingsDialog = ref(false);
this should be renamed and pushed to the state const

2025-01-24 09:55 UTC, Kuchenpirat commented on frontend/pages/shopping-lists/index.vue
> +    const shoppingList = ref<ShoppingListOut | null>(null);
this should be renamed to "ownerTarget" and pushed to the state const

2025-01-24 09:55 UTC, Kuchenpirat commented on frontend/pages/shopping-lists/index.vue
> +    async function toggleSettingsDialog(list: ShoppingListOut) {
```suggestion
    async function toggleOwnerDialog(list: ShoppingListOut) {
```

2025-01-24 16:08 UTC, Wetzel402 commented on frontend/pages/shopping-lists/index.vue
> +        :title="$t('general.settings')"
Changed to...
```
:icon="$globals.icons.admin"
:title="$t('user.edit-user')"
```

2025-01-26 13:59 UTC, Kuchenpirat approved these changes
Looking all good now :)
This really is a big UI improvement, thanks for your work on this 😊

2025-01-26 14:04 UTC, merged

2025-01-26 14:06 UTC, Wetzel402 commented
@Kuchenpirat, Thank you as well.  Excited to see Mealie improve.

2025-02-06 09:51 UTC, boc-the-git commented
Good stuff @Wetzel402 ! Looking good!