Enable OIDC with Synology SSO Server
mealie-recipes/mealie pull request #4544
Opened 2024-11-12 12:35 UTC by JoTec2002

## What type of PR is this?

_(REQUIRED)_

- feature
- bug

## What this PR does / why we need it:

Mealie required the `name` claim from an OIDC Provider, but the Synology SSO Server doesn't Provide this claim.

After this Pull Request Mealie will no longer required the `name` claim to be present.

To not cause any issues or lose any OIDC user information the following logic is used:
If the `name` claim is present it will be used, otherwise the username will be used as name.

## Which issue(s) this PR fixes:

Fixes #4543

2024-11-12 21:51 UTC, MuadDibVV commented
+1

2024-11-14 22:34 UTC, cmintey commented
I think it would be better and more extensible to introduce a new env var `OIDC_NAME_CLAIM`, which would default to `name`, but you could override it to whatever you want.

2024-11-19 00:29 UTC, michael-genson commented
@JoTec2002 if you could take a look at the feedback from @cmintey we should be able to get this merged!

2024-11-19 08:35 UTC, JoTec2002 commented
@cmintey I completed the changes you suggested.

2024-11-19 13:46 UTC, cmintey requested changes
Looking good! One more small thing to address

2024-11-19 13:46 UTC, cmintey commented on mealie/core/security/providers/openid_provider.py
> +        claims = {"email", settings.OIDC_USER_CLAIM}
Can you add the new env var to this set, since it's required?

2024-11-19 13:51 UTC, JoTec2002 commented on mealie/core/security/providers/openid_provider.py
> +        claims = {"email", settings.OIDC_USER_CLAIM}
Done

2024-11-19 14:02 UTC, cmintey approved these changes
Thanks for working on this!

2024-11-19 14:07 UTC, michael-genson approved these changes

2024-11-19 14:15 UTC, merged