fix: Meal Plan Notes allow Submission Without Title/Note Text
mealie-recipes/mealie pull request #4615
Opened 2024-11-26 19:22 UTC by Arshad561

## What type of PR is this?

- bug

## What this PR does / why we need it:

Currently, when creating a new meal planner, the user can attempt to create a meal without providing a meal recipe or title. This results in a `422` error from the server.

With this fix:
- The "Create" button will be disabled if the meal recipe or title is empty.
- This ensures a smoother user experience and prevents invalid submissions.

Before my change <br>
<img width="516" alt="Screenshot 2024-11-26 at 12 20 41 PM" src="https://github.com/user-attachments/assets/c5597808-7a46-4591-adf8-4f74c22ecc03">

After my change <br>
[
<img width="516" alt="Screenshot 2024-11-26 at 12 20 55 PM" src="https://github.com/user-attachments/assets/c87a309a-4e44-48f6-9398-df7d647ce71d">
](url)

## Which issue(s) this PR fixes:

Fixes #2446

## Special notes for your reviewer:

Please focus on the changes made to the validation logic for enabling/disabling the "Create" button and ensure that the edge cases for validation are covered.

## Testing:

- Tested the meal planner form to verify that the "Create" button is only enabled when:
  - A meal recipe is selected, or
  - A meal title is entered.
- Attempted to submit invalid data (empty fields) to confirm that the button remains disabled.

2024-12-03 21:12 UTC, hay-kot requested changes

2024-12-03 21:12 UTC, hay-kot commented on frontend/pages/household/mealplan/planner/edit.vue
> +
Pretty sure this needs to be converted to a computed property to handle reactivity correctly.

2024-12-03 22:09 UTC, Arshad561 commented
@hay-kot I have made the change. Can you have a look at it?

2024-12-04 01:58 UTC, hay-kot approved these changes

2024-12-04 02:07 UTC, merged