Message alerts for image upload using image upload button and url button
mealie-recipes/mealie pull request #4665
Opened 2024-12-03 08:19 UTC by amishabagri

## What type of PR is this?

bugfix, 
Found an additional bug

## What this PR does / why we need it:

This Pull request addresses the issue of issue #4494 where even if the image upload fails no message or alert was displayed.
This also covers the issue related to the URL. If URL of the image is provided, it didn't use to check if the URL is valid or not and consequently did not displayed any message. So through this PR request the following things are covered:

1. When uploading the image the .file is checked if it is valid or not. If the file ends with .jpg, .jpeg, .png etc, the image file is accepted and is uploaded. After uploading the file the message is also displayed.
2. If the image extension is not same as the .jpg, .png, etc, then the error message is diplayed for using wrong file extension.
3. For using the URL,, the URL is checked if it is valid or not using the HTTP codes. If the URL is valid, the image is uploaded and the success message is displayed.
4. If the URL is not valid, then the error message is displayed.

Before: No messages are displayed
1. Uploading with a URL
<img width="1510" alt="Screenshot 2024-12-03 at 12 54 17 AM" src="https://github.com/user-attachments/assets/3972b0a1-997a-49f2-8b4f-055a07807378">

2. Uploading with Upload Image button
<img width="1510" alt="Screenshot 2024-12-03 at 1 08 17 AM" src="https://github.com/user-attachments/assets/49b5ec09-fb4d-451c-ad67-256c33fb8e7c">

After: Messages are displayed
1. Uploading when URL is invalid
<img width="1510" alt="Screenshot 2024-12-03 at 12 53 19 AM" src="https://github.com/user-attachments/assets/31e4ced5-eb8c-4301-a079-469374aeed11">

2. When URL is valid and image is also changed:
<img width="1510" alt="Screenshot 2024-12-03 at 1 03 44 AM" src="https://github.com/user-attachments/assets/f8a3743e-e2af-4390-8c2e-ab732515cfeb">

3. Using valid file extension:

<img width="1510" alt="Screenshot 2024-12-03 at 1 09 53 AM" src="https://github.com/user-attachments/assets/d2a116aa-a953-40dc-a0c9-5ccf7acb0c23">

4. Using invalid file extension:

<img width="1510" alt="Screenshot 2024-12-03 at 1 10 02 AM" src="https://github.com/user-attachments/assets/d5e36424-35cb-4277-a334-49b681fea2a3">

## Which issue(s) this PR fixes:

Fixes #4494 

## Testing

Since this was changes in UI, I tested with different URLs , valid and invalid to verify if the message is displayed.
I tested with different file extension to make see if there is invalid file extension the message is displayed.

## Note:
Please ignore the WakelockSwitch.vue

2025-01-05 21:08 UTC, Kuchenpirat requested changes
Hey, thanks for your contribution. 

I just had a quick glance at it and this looks mostly good. I just have one thing to add and a few minor code comments for my first feedback round. 


The Image button is no longer properly aligned with the settings button. This would need to be updated.

2025-01-05 21:08 UTC, Kuchenpirat commented on frontend/components/Domain/Recipe/RecipeImageUploadBtn.vue
> +       const allowedExtensions = [".jpg", ".jpeg", ".png", ".gif", ".webp"];
fix indentation
```suggestion
      // Check if the file has an acceptable extension
      const allowedExtensions = [".jpg", ".jpeg", ".png", ".gif", ".webp"];
```

2025-01-05 21:08 UTC, Kuchenpirat commented on frontend/components/Domain/Recipe/RecipeImageUploadBtn.vue
> +       const allowedExtensions = [".jpg", ".jpeg", ".png", ".gif", ".webp"];
I think you are missing `heic` and `avif`.

2025-02-03 22:06 UTC, amishabagri commented
I have made the changes. Please review it

2025-08-07 14:40 UTC, michael-genson commented
Hey there! As you might know, we've been working on the upgrade to Nuxt 3 for the past several months, and had to hold on reviewing/merging PRs during that time (especially frontend ones). That work is more-or-less completed, so we've started reviewing PRs again.

This PR has merge conflicts preventing us from fully reviewing/testing it. If you're able to resolve those we can get to work on it.

Appreciate your patience, we know it's been a bit, but now that the Nuxt 3 upgrade is completed we should be able to get things reviewed much quicker than before.

2025-10-10 03:55 UTC, closed without merging

2025-10-10 03:55 UTC, michael-genson commented
Hey there, this PR has been sitting for a while and has some merge conflicts to be resolved. Since it's been a bit, I'm going to close this PR. Feel free to create a new PR, or you can re-open this one if you're able to resolve the conflicts.