feat: Option to automatically create share links for recipes in recipe actions
mealie-recipes/mealie pull request #4676
Opened 2024-12-03 23:28 UTC by ianp1

## What type of PR is this?

- feature
- bug

## What this PR does / why we need it:

Currently, when using a recipe action on a recipe that is not publicly available (due to recipe, group or household being private), the receiving service will not be able to read the recipe data. 

As discussed in #4619, this PR implements an additional template option for recipe actions. The option `${share-link-expires-seconds-<x>}` is automatically replaced by a newly created share link that expires after `x` seconds. This makes share links usable even on private recipes, groups and households. 

## Which issue(s) this PR fixes:

Fixes  #4619

## Special notes for your reviewer:
I am not completely certain, if the method to obtain the group slug is correct. Please check this part thoroughly.
Also, i have not yet created documentation for the new option - is the website documentation part of this repository?

## Testing
I created a private recipe, a public recipe and multipe recipe actions

- One containing a single share link template
- One containing multiple share link templates with different expiry times
- And one containing multiple share link templates, some of which having the same expiry times

I also tested with different privacy settings in group and household. The receiver of the given action was always able to read the recipes, without being logged in using the share link.

2025-01-19 19:22 UTC, michael-genson requested changes
Looks great! Sorry for taking so long on this, holidays beat me up. One change to remove an API call and we're all set.

Would you also be able to add this to the docs? Just add it to the list of merge fields and a short (one sentence) description. And then also maybe change the Bring example to use the new field (instead of `url`).
https://docs.mealie.io/documentation/getting-started/features/#recipe-actions

2025-01-19 19:22 UTC, michael-genson commented on frontend/composables/use-group-recipe-actions.ts
> +    const group = (await api.groups.getOne(recipe.groupId || "")).data;
You should be able to grab the slug from the URL instead of fetching it via the API:

```js
import { useRoute } from "@nuxtjs/composition-api";

// put this right under "useUserApi"
const route = useRoute();

// replace the API call with this
const groupSlug = route.value.params.groupSlug || recipe.groupId || "";
```

2025-01-25 08:12 UTC, ianp1 commented
Thanks, good to hear! I am unfortunately unavailable till the start of February, but I will have a look at it then

Greetings

2025-04-22 12:41 UTC, Abalysa commented
Is there any follow up on this PR?
I am facing the same issue that (even tough my mealie instance itself is accessible to the internet) i dont want to mark all my recipes as public just for the Bring! integration.

2025-05-02 10:51 UTC, ianp1 commented
Hey there,

i am sorry, live has been busy and i have forgotten about this pull request. I have now added the requested documentation. @michael-genson is everything as expected?

I have also pulled my branch up to current state of mealie-next and tested everything again. However, rebasing seems to have messed up this merge request commits - should i try to recreate this PR with a clean branch?

Greetings

2025-05-02 19:19 UTC, michael-genson commented
Something seems up with the recent commits, it doesn't look like the main branch was merged in.
Apologies for the delay, the maintainers (myself included) have been quite busy, and frontend PRs are currently blocked by [the Nuxt 3 upgrade](https://github.com/mealie-recipes/mealie/pull/5184).

2025-05-14 15:00 UTC, ianp1 commented
Do you have any advice on how to proceed? I would create a new PR with cleaned up history, or do you have a better idea?

2025-05-15 03:29 UTC, michael-genson commented
Either that, or you can revert the commits and make sure you merge mealie-next into your branch

2025-07-07 21:50 UTC, michael-genson commented
I tried force-pushing a fixed commit history but that didn't seem to work. My recommendation would be to close this PR/branch and create a new branch with your changes. It will also help avoid the merge conflicts with the Nuxt upgrade

2025-10-10 03:59 UTC, michael-genson commented
Hey there, this PR has been sitting for a while and has some merge conflicts to be resolved. Since it's been a bit, I'm going to close this PR. Feel free to create a new PR, or you can re-open this one if you're able to resolve the conflicts.

2025-10-10 03:59 UTC, closed without merging