feat: Add delete button to recipe image modal
mealie-recipes/mealie pull request #4708
Opened 2024-12-11 03:39 UTC by Tomnowell

## What type of PR is this

- feature

## What this PR does / why we need it:

Currently there is no way to delete an image for a recipe once it has been uploaded (although uploading/scraping a new image will replace the current image). This PR adds a way to remove an image that has been uploaded or scraped.

Files changed:

- frontend/components/Domain/Recipe/RecipeImageUploadBtn.vue
Increase the width of the modal and add the delete button emit a delete event.

- frontend/components/Domain/Recipe/RecipePage/RecipePageParts/RecipePageEditorToolbar.vue
Call the API to delete.

- frontend/lib/api/user/recipes/recipe.ts
Handle response.

- mealie/repos/repository_recipes.py
Update the repository.

- mealie/routes/recipe/recipe_crud_routes.py
Add new CRUD route to add delete functionality.

- mealie/services/recipe/recipe_data_service.py
Add data service function to delete the image.

After:
![Screenshot from 2024-12-11 12-15-22](https://github.com/user-attachments/assets/54dfa203-a992-4597-a6a0-afb885a0b9f9)

## Which issue(s) this PR fixes:

Fixes # [4595](https://github.com/mealie-recipes/mealie/issues/4595) 

## Special notes for your reviewer:

This is my first ever PR on a public project! Sorry for all the errors! Please let me know where I can do better!

## Testing

Manual testing through the UI

2025-01-19 19:31 UTC, michael-genson requested changes
It looks like when the image is deleted the page doesn't react. For example, try uploading a tall image and then deleting it. The page should shrink since there's no image, but it doesn't shrink until the page refreshes.

2025-01-19 19:31 UTC, michael-genson commented on frontend/components/Domain/Recipe/RecipeImageUploadBtn.vue
> +          <v-btn class="ml-2" color="error" :loading="loading" :disabled="!slug" @click="deleteImage">
Can we disable this button if there's no image?

2025-01-19 19:31 UTC, michael-genson commented on mealie/services/recipe/recipe_data_service.py
> +            self.logger.exception(f"Failed to delete image data: {e}")
You can leave off the exception, `logger.exception` already logs the full traceback

```suggestion
            self.logger.exception(f"Failed to delete image data")
```

2025-01-20 12:29 UTC, ChipSkylark37 commented
+1 Would love to see this get fixed up and merged in. Anywhere there is an image in the UI, I would expect to be able to delete it.

2025-01-20 13:10 UTC, Tomnowell commented on frontend/components/Domain/Recipe/RecipeImageUploadBtn.vue
> +          <v-btn class="ml-2" color="error" :loading="loading" :disabled="!slug" @click="deleteImage">
Good idea! Will do :D

2025-01-20 13:11 UTC, Tomnowell commented on mealie/services/recipe/recipe_data_service.py
> +            self.logger.exception(f"Failed to delete image data: {e}")
Thanks!👍

2025-03-09 01:53 UTC, ChipSkylark37 commented
Does this still need the fix before getting merged in?

2025-03-09 07:12 UTC, Tomnowell commented
So sorry everyone, I'm working on my master's project! I'll

2025-10-04 02:04 UTC, ChipSkylark37 commented
Any chance this would be ready to merge in?

2025-10-10 03:59 UTC, michael-genson commented
Hey there, this PR has been sitting for a while and has some merge conflicts to be resolved. Since it's been a bit, I'm going to close this PR. Feel free to create a new PR, or you can re-open this one if you're able to resolve the conflicts.

2025-10-10 03:59 UTC, closed without merging