feat: Add recipe as ingredient
mealie-recipes/mealie pull request #4800
Opened 2024-12-30 21:58 UTC by parumpum

## What type of PR is this?

- feature

## What this PR does / why we need it:

Adds the ability to reference another recipe in a recipe's ingredients. A reference to the recipe is added to a new column for table recipes_ingredients. This can be utilized to determine if the ingredient is a food, a recipe, or just a note.

Adding recipe to shopping list will loop through the ingredients list, cascading down into recipes if it finds any to add individual ingredients to the shopping list.

<img width="299" alt="image" src="https://github.com/user-attachments/assets/6889afc9-e5ce-4a1a-87d9-49191cc46984" />

![image](https://github.com/user-attachments/assets/b9b21fd7-defc-4168-b1e6-666f01e3cc5f)

<img width="399" alt="image" src="https://github.com/user-attachments/assets/c63d84bc-9604-4dfc-b3da-494c4a1b6e78" />

Clicking the referenced recipe will open a new tab to the recipe

## Which issue(s) this PR fixes:

https://github.com/mealie-recipes/mealie/discussions/1761

## Testing

Tested by linking recipes together, adding ingredients to shopping lists
Unit test that adds a recipe to another recipe as an ingredient
Modified referenced recipe name and ingredients, verified changes were picked up on main recipe page

2024-12-31 21:03 UTC, parumpum commented
Addressed feedback in Discord:

- Added select all / none to Shopping List sections
- Added selectable list of child recipes on "I Made This" dialog
- Images shown when searching for child recipes to help pick the correct item

2025-01-28 13:05 UTC, felixschndr commented
Thanks for the great work! Looking forwards to this being merged

2025-03-15 12:00 UTC, felixschndr commented
@parumpum would you mind fixing the merge conflicts so the MR can be reviewed (@hay-kot)?

2025-03-15 13:04 UTC, Kuchenpirat commented
we won't merge anything with frontend code before the nuxt 3 upgrade has been done (which will bring new conflicts)

2025-03-15 13:27 UTC, felixschndr commented
I see, thanks for the clarification (FYI for anyone looking for that PR: https://github.com/mealie-recipes/mealie/pull/5184)

2025-04-30 02:49 UTC, jawilson commented
Please don't close this PR! I really want this ability.

2025-04-30 05:43 UTC, Kuchenpirat commented
No worries we are not closing this.
Maintainers are currently just pretty busy with stuff outside of mealie as well as the nuxt 3 upgrade.

2025-07-13 16:57 UTC, tecosaur commented
As one of the people eagerly awaiting this, now that v3 is out, how's this PR looking?

2025-07-16 16:02 UTC, parumpum commented
Once I find some free time to update it I’ll get it going!

On Sun, Jul 13, 2025 at 09:58 Timothy ***@***.***> wrote:

> *tecosaur* left a comment (mealie-recipes/mealie#4800)
> <https://github.com/mealie-recipes/mealie/pull/4800#issuecomment-3067166923>
>
> As one of the people eagerly awaiting this, now that v3 is out, how's this
> PR looking?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/mealie-recipes/mealie/pull/4800#issuecomment-3067166923>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A4PIWMTU2F7NWAGHM43YWGD3IKF2JAVCNFSM6AAAAABUMT6IPOVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZTANRXGE3DMOJSGM>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2025-08-07 14:42 UTC, michael-genson commented
Hey there! As you might know, we've been working on the upgrade to Nuxt 3 for the past several months, and had to hold on reviewing/merging PRs during that time (especially frontend ones). That work is more-or-less completed, so we've started reviewing PRs again.

This PR has merge conflicts preventing us from fully reviewing/testing it. If you're able to resolve those we can get to work on it.

Appreciate your patience, we know it's been a bit, but now that the Nuxt 3 upgrade is completed we should be able to get things reviewed much quicker than before.

2025-09-10 09:04 UTC, tecosaur commented
Friendly poke :point_right: @parumpum :slightly_smiling_face:

2025-09-10 21:00 UTC, parumpum commented
Just got my dev environment set back up to work on this. Definitely some broken pieces to work on with all the Nuxt 3 changes that went in!

2025-09-18 15:38 UTC, 1112luke commented
I would love this!! Any information on the timeline for this to be merged?

2025-10-06 02:52 UTC, Coryrichter94 commented
This is a great feature! Can not wait

2025-10-24 18:17 UTC, michael-genson requested changes
Looks good so far! I made a few cleanup changes, including removing the `isRecipe` flag. We used to have a bunch of flags on the backend for things like this and it got super messy so we removed them. Similarly to how we handled those, I adjusted the frontend logic to accommodate.

For adding a recipe as an ingredient, instead of adding a dropdown to the "Add" button, would it be better to add it to the existing context menu? This would have the advantage of using an existing ingredient as a recipe instead of adding a new one. Something like "toggle recipe"
<img width="299" height="252" alt="image" src="https://github.com/user-attachments/assets/7a7e2be0-fa97-4408-8cf6-aca446124cbf" />

Another question: when we set a recipe to qty 0, that's signaling to the frontend that we should just not render the quantity (good for things like "teriyaki sauce" which might not have a defined amount). If we add that to the shopping list with 0 qty, will that work, or will nothing for that recipe be added? Might want an edge case for when the qty is 0 to use a shopping list qty of 1.

One more note below as well. I haven't fully finished reviewing this but these were my first impressions :) Love how it looks so far!

2025-10-24 18:17 UTC, michael-genson commented on mealie/schema/recipe/recipe_ingredient.py
> +        return self
Is this desired behavior? What if we want to add a note to the recipe and have it render? e.g. "Make this thicker since we're using it as a base" or "slice extra thin".

2025-10-26 14:27 UTC, parumpum commented
> Looks good so far! I made a few cleanup changes, including removing the `isRecipe` flag. We used to have a bunch of flags on the backend for things like this and it got super messy so we removed them. Similarly to how we handled those, I adjusted the frontend logic to accommodate.
> 
> For adding a recipe as an ingredient, instead of adding a dropdown to the "Add" button, would it be better to add it to the existing context menu? This would have the advantage of using an existing ingredient as a recipe instead of adding a new one. Something like "toggle recipe" <img alt="image" width="299" height="252" src="https://private-user-images.githubusercontent.com/71845777/505436413-7a7e2be0-fa97-4408-8cf6-aca446124cbf.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjE0ODc1MjEsIm5iZiI6MTc2MTQ4NzIyMSwicGF0aCI6Ii83MTg0NTc3Ny81MDU0MzY0MTMtN2E3ZTJiZTAtZmE5Ny00NDA4LThjZjYtYWNhNDQ2MTI0Y2JmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTEwMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUxMDI2VDE0MDAyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUyZGZlMjE4ZmJiMjY0MWEwMTJjNTEzYWYyM2I0YzkzMDcyMjQ3M2I4Yzk3ZGZlYTlkOWM1ZDZjZjc0NDEyZjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.cBFHYvtXDOihdNCJcxTD6q88eiDeXcpdL0HfjynTTPQ">
> 
> Another question: when we set a recipe to qty 0, that's signaling to the frontend that we should just not render the quantity (good for things like "teriyaki sauce" which might not have a defined amount). If we add that to the shopping list with 0 qty, will that work, or will nothing for that recipe be added? Might want an edge case for when the qty is 0 to use a shopping list qty of 1.
> 
> One more note below as well. I haven't fully finished reviewing this but these were my first impressions :) Love how it looks so far!

Setting qty to 0 seems to work as expected. It doesn't show the quantity on the ingredient list, and still allows adding to shopping list as expected.

For the Add button, I feel like expanding the Add Food button is more intuitive than moving this function entirely to the Toggle Section/Insert menu. It does make sense to add a Toggle Recipe option there, so I'll work on that soon.

2025-11-02 21:57 UTC, michael-genson requested changes
Pushed a few more changes/fixes. Just two more things I ran into that I didn't get time to address:
- One regarding printing, see below
- When saving a recursive ingredient, the backend appropriately handles this case and returns an error, but the frontend still looks like it updated successfully. Can we catch these errors on the frontend so the user doesn't think it worked? (we probably don't want to leave edit mode)

2025-11-02 21:57 UTC, michael-genson commented on frontend/components/Domain/Recipe/RecipePrintView.vue
> +  };
When printing the linked recipes, if the linked recipe appears in the middle of a section, the section titles become mangled. For instance:
```markdown
Recipe
 - [Section A]
    - ing 1
    - ing 2
    - linked recipe
    - ing 3
```

Becomes:
```markdown
[Section A]
- ing 1
- ing 2
[Linked Recipe]
- linked recipe ing 1
- ...
- ing 3 (from the recipe, not from the linked recipe)
```

Maybe we just keep it simple and remove this functionality from printing?

2025-11-04 03:43 UTC, parumpum commented on frontend/components/Domain/Recipe/RecipePrintView.vue
> +  };
I will remove this functionality. It can be returned with a rework of Sections that better defines which section each ingredient is part of instead of depending on a single ingredient with the "title" property set to define a Section.

Appreciate your assistance getting this through to the finish line.

2025-11-04 05:45 UTC, michael-genson approved these changes
LGTM, thanks for sticking with this one! I know it took a while but we got it in there 😅

2025-11-04 05:57 UTC, merged

2025-11-17 12:20 UTC, ambroisie commented
It's unclear to me how to handle linked recipes amounts. Or rather, I think I understand the intended way to deal with it but find it awkward to read.

Here are a couple of examples:

* "Salted caramel macarons": depends on "Macaron shells". The (unscaled) recipe yield 50 top/bottoms. The salted caramel recipes is scaled for 50 top/bottoms. If I link "1 Macaron shells" that is the correct amount of that recipe to make, but reads weirdly on the page. If I link "50 macaron shells" it links correctly but doesn't reflect the fact that I should 50x the shell recipe.
* "Pain aux raisins": depends on both "Croissant dough" and "Pastry cream". The scales should be 0.5x dough (500 grams from a 1kg yield recipe) and 0.25x cream (200 grams from an 800 gram yield recipe). Once again it reads weirdly to only have "0.5 Croissant dough" on the recipe page, instead of "500 gram croissant dough".

2025-11-17 14:26 UTC, parumpum commented
> It's unclear to me how to handle linked recipes amounts. Or rather, I think I understand the intended way to deal with it but find it awkward to read.
> 
> Here are a couple of examples:
> 
>     * "Salted caramel macarons": depends on "Macaron shells". The (unscaled) recipe yield 50 top/bottoms. The salted caramel recipes is scaled for 50 top/bottoms. If I link "1 Macaron shells" that is the correct amount of that recipe to make, but reads weirdly on the page. If I link "50 macaron shells" it links correctly but doesn't reflect the fact that I should 50x the shell recipe.
> 
>     * "Pain aux raisins": depends on both "Croissant dough" and "Pastry cream". The scales should be 0.5x dough (500 grams from a 1kg yield recipe) and 0.25x cream (200 grams from an 800 gram yield recipe). Once again it reads weirdly to only have "0.5 Croissant dough" on the recipe page, instead of "500 gram croissant dough".

I think this is more of a servings vs yield issue. Showing "0.5 Croissant dough" on your Pain Aux Raisins recipe indicates that you would scale your croissant dough recipe to 0.5 and make that. If you utilize the shopping list, the ingredients will be scaled to this value.

Likewise for the macarons, you could create or change the recipe to have amounts for 1 macaron shell so that it makes sense to enter 50 macaron shells on the salted caramel macaron recipe. You would be able to set the scale of the macaron shell recipe to the number of shells you ultimately want.

Linking a recipe is simply the quantity of that recipe to make. The current idea behind the feature is that you would be able to go into the main recipe you are ultimately going to make and click on the linked recipe to open a new tab to make that item in the required quantities. One enhancement I could see here would be to pull up the recipe scaled as indicated in the main recipe to save a manual adjustment there.

2025-11-17 15:13 UTC, ambroisie commented
Yeah I understand, I just find it awkward.

I wish the linked recipe would surface the yield amount and be able to scale that instead.

2025-11-20 07:22 UTC, xF4m3 commented
Would it be possible to show the ingredients of the linked recipie aswell? Sortes under the linked recipie title or something? I think this would make working with it easier as you do not necessarly have to open the linked recipie.

Also just wanted to say thank you guys for getting this feature implemented in the First place, have been following and waiting for this to happen all this time. Great work, really appreciate this.

2025-11-20 07:40 UTC, ambroisie commented
> Sorted under the linked recipie title or something

In a foldable menu?

2025-11-20 07:47 UTC, xF4m3 commented
Doesn't have to be foldabale but that could be one way to do that. In my mind i was just thinking about an expanded static list that is maybe writtin in a smaller or grayer text so it doesn't draw the main attention, but i am probably fine with whatever idea like being collapsible like you mentioned.

2025-11-21 15:26 UTC, MatzeG1t commented
> Would it be possible to show the ingredients of the linked recipie aswell? Sortes under the linked recipie title or something? I think this would make working with it easier as you do not necessarly have to open the linked recipie.
> 
> Also just wanted to say thank you guys for getting this feature implemented in the First place, have been following and waiting for this to happen all this time. Great work, really appreciate this.

I would suggest to think about the usecase of this. Seeing all ingredients might sound helpful at first, but whats the goal for the user? If its "adding also the ingredient/recipe to the shopping list" a confirmation would make sense at another spot.
Just seeing the ingredients might be only helpful if its a simple ingredient-recipe. If I think about "turkey" or something, the sauce and side dishes are complex as well - only seeing the ingredients in the "turkey recipe" wont help I'd say.

Did the dev team ever thing about adding a feedback function in the tool? This way maybe more user feedback could be sourced. Not just by the mealie-hosts (who check release logs) but rather also the cooks using it - if they are not the same person :)